### ISSUE TITLE
The Twilight Forest Possible Incompatibility

### ISSUE THREAD

**Issue by Thalonias** [Thelnfamous1/All-Bark-All-Bite#3]
[crash-2023-03-21_01.47.16-server.txt](https://github.com/Thelnfamous1/All-Bark-All-Bite/files/11029716/crash-2023-03-21_01.47.16-server.txt)

Not 100% sure what caused the crash other than an odd interaction with the wolfs from the The Twilight Forest mod. Testing was done to try to recreate the crash but no 2nd crash happened.

**Comment by Thelnfamous1** [comment]
This is not necessarily an incompatibility, but rather some "unsafe" coding on my end. I can make it more "safe" to prevent this crash from happening.

**Comment by Thelnfamous1** [comment]
I believe I've resolved the issue with build 0.9.2, should be on Curseforge soon. You can try to recreate the crash by instantly killing a stalking wolf or dog's target while they are mid-air pouncing on them. Note that stalking only occurs when the wolf or dog is not near other wolves or dogs.
