### ISSUE TITLE
Doesnt work on Servers on 1.20.1

### ISSUE THREAD

**Issue by rainysux** [Thelnfamous1/All-Bark-All-Bite#6]
I am unable to run the mod in a server setting but it works fine on singleplayer

**Comment by Thelnfamous1** [comment]
Need a crash log / latest log to diagnose issue

**Comment by melvinadame** [comment]
I'm also having the same issue.

**Comment by Thelnfamous1** [comment]
Should be fixed in latest version (1.20.1-1.0.2).
