### ISSUE TITLE
Crash On Launch

### ISSUE THREAD

**Issue by Sweek9** [Thelnfamous1/All-Bark-All-Bite#7]
Causes crash on launch even as the only mod present. Minecraft v1.20.2, Forge v48.0.35.
[latest.log](https://github.com/Thelnfamous1/All-Bark-All-Bite/files/13304158/latest.log)
[crash-2023-11-08_21.30.57-fml.txt](https://github.com/Thelnfamous1/All-Bark-All-Bite/files/13304161/crash-2023-11-08_21.30.57-fml.txt)

**Comment by Thelnfamous1** [comment]
This is an incompatibility with 1.20.2 due to a removed Forge feature, I have fixed it in dev but am temporarily unable to release it.

**Comment by Sweek9** [comment]
I look forward to trying it out once you've released it on CurseForge. You should remove the designation of compatibility with Minecraft v1.20.2 on mod versions 1.0.0-1.0.2 too, to save people from the grief. 
![Screenshot 2023-11-09 at 9 41 03 PM](https://github.com/Thelnfamous1/All-Bark-All-Bite/assets/2678959/84cf30a6-e6cd-43d9-8943-51dc26a23c95)
